import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import StoreProvider from "./StoreProvider";
import UserProvider from "./UserProvider";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "IntervPrep",
  description: "Generated by Shubham Choudhary in Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable}  antialiased`}
      >
        <StoreProvider><UserProvider>{children}</UserProvider></StoreProvider>
        <Toaster/>
      </body>
    </html>
  );
}
